version: '3'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=password
      - DB_NAME=kanban_tracker
      - JWT_SECRET=docker_jwt_secret
      - SESSION_SECRET=docker_session_secret
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: mariadb:10.6
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=kanban_tracker
    volumes:
      - db_data:/var/lib/mysql
      - ./docker-database.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped

volumes:
  db_data: